### ISSUE TITLE
allow plates and sera to be categorized into groups

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/seqneut-pipeline#31]
Looking at current GitHubs, I think it would be helpful to allow plates and/or sera to be categorized into groups, such as "pilots_for_determining_library_dilution" etc. That way the data/plots for troubleshooting are not mixed with the ones for actual results.

@anloes @ckikawa, any thoughts on this idea or how to do it before I start to implement?

**Comment by ckikawa** [comment]
Agreed! Rather than adding more keys to each per-plate config, would it be better to instead have some sort of centralized dictionary in the config that defines group keys as consisting of certain plates/sera? 

This would be nice for identifying samples as belonging to library optimization (as you pointed out) or as belonging to different serum sample cohorts/studies. Particularly if this could be used to interactively toggle sera on the `aggreagte_titers` plots. It would be helpful to filter the many sera NT50 plots to just those relevant to library optimization, just those relative to specific cohorts, etc.
