### ISSUE TITLE
reasonable suggestions for `fixslope` range for example / docs

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/seqneut-pipeline#36]
In #35, it was implemented to enable `fixslope` to constrain the slope to a range (see #32).

However, more analysis of real data is needed to see if the suggested range in the example (`[0.8, 5]`) is actually reasonable for serum.

Check this on real data and adjust accordingly.

**Comment by anloes** [comment]
For fixslope, I initially tested [0.8-6] as the starting range, as for the DRIVE cohort data, where this parameter was not constrained, this range appeared to capture the majority of well-fit curves (~65%). 

I also tested [0.8,10] with the most recent data, and I do have a large number of curves fitting with the max slope within the range permitted (either 6 or 10, respectively), but I think that may be partially a result how the error in the most recent plates is impacting the shape of these curves, i.e. we have many curves with no points in the slope or only a single point in the slope. The resulting midpoint titers are quite similar, as would be expected. I would expect that the larger this max slope is the more variability we might observe between slopes fit for samples with sharp curves like this, so a smaller range is likely preferable. Though, I will repeat this test once we have additional plates to confirm that these parameters are reasonable.

**Comment by ckikawa** [comment]
Similar to @anloes, I have also been constraining `fixslope` to a fairly loose range of `[0.8, 10]`. I agree that the difference between midpoints called with `[0.8, 10]` versus `[0.8, 5]` is likely to be minimal, but for now, I will probably continue to use this wider range until I have more data. I'm currently only testing with 9 individuals. 

In the future, since there's no real biological reason (?) to point to for allowing such steep slopes, I agree that reducing the upper bound is probably better.
